@startuml
'说明书
'https://plantuml.com/sequence-diagram

'文本对齐
skinparam responseMessageBelowArrow true

'隐藏未链接的成员
'hide unlinked

'自动编号
autonumber 1
'https://plantuml.com/sequence-diagram

'为了符合严格UML的标准（线头的形状必须是三角形，而不能是箭头形
skinparam style strictuml

'别名
participant RentrantLock as rt
participant RentrantLock.Sync as Sync
participant RentrantLock.NonfairSync as NonfairSync
participant AbstractQueuedSynchronizer as AQS
participant Unsafe


activate rt
rt -> rt: ReentrantLock()
rt -> rt: NonfairSync()

rt -> rt: lock()

rt -> rt: NonfairSync.lock()

rt -> AQS: compareAndSetState(0, 1)
deactivate rt

autonumber 5.1
AQS -> Unsafe: compareAndSetState()
activate Unsafe
||20||
'Unsafe -> AQS: true/false
return true/false

deactivate Unsafe

AQS -> AQS: setExclusiveOwnerThread(Thread)

autonumber 5
rt -> AQS++: acquire(1)

autonumber 5.1
AQS -> AQS: tryAcquire
AQS -> NonfairSync: nonfairTryAcquire()
NonfairSync -> Sync: nonfairTryAcquire()
Sync -> AQS: getState()
AQS --> Sync: oldState
Sync -> AQS: setState(newState)
note right: if current = exclusiveOwnerThread()



AQS -> AQS: NonfairSync
AQS -> AQS: acquireQueued(addWaiter(Node))
note right: Acquires in exclusive uninterruptible mode\n for thread already in queue. \nUsed by condition wait methods as well as acquire.
AQS -> AQS: selfInterrupt()

autonumber 6
AQS --> rt: void

@enduml